version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    build:
        context: .
        dockerfile: ./Db/Dockerfile
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=SuperPass92!
      - ACCEPT_EULA=Y
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
      - db
    environment:
      - ConnectionStrings__Default=Server=db;Database=myapi;User Id=sa;Password=SuperPass92!
